---
title: "Tiago Verissimo"
subtitle: "*Mathematician that can code, sometimes*"
page-layout: full
about:
  template: solana
  links:
    - icon: reddit
      text: Reddit
      href: https://www.reddit.com/user/Tiago_Verissimo/
    - icon: linkedin
      text: LinkedIn
      href: https://www.linkedin.com/in/tiagoverissimo
    - icon: github
      text: Github
      href: https://github.com/TiagoVerissimo
    - icon: medium
      text: Medium
      href: https://medium.com/@tiagoverissimokrypton
---

I am a PhD Student in Mathematics at Newcastle University, working in Multivariate Truncated Moment Problems at the moment (no pun intended). I plan to work in different things in the future, but who knows.

Here, you'll find explorations in pure, applied and computational mathematics. Sometimes I will go into other topics such as computer science, philosophy and mathematical pedagogy.

## Education

**Newcastle University** | Newcastle upon Tyne, UK  
*PhD in Pure Mathematics* | 2024 - 2028

**Stockholm University and KTH Royal Institute of Technology** | Stockholm, Sweden  
*MSc in Mathematics* | 2022 - 2024

**Univeristy of Lisbon** | Lisbon, Portugal  
*BSc in Applied Mathematics* | 2019 - 2022

## Academic Publications

* **Extension of Symmetries in the Expanding Universe**  
  Mesquita Santos Verissimo, Tiago, 2024. Master’s Thesis. KTH Royal Institute of Technology and Stockholm University, Stockholm. [[Master's Thesis](https://kth.diva-portal.org/smash/record.jsf?aq2=%5B%5B%5D%5D&c=21&af=%5B%5D&searchType=LIST_LATEST&sortOrder2=title_sort_asc&query=&language=sv&pid=diva2%3A1917410&aq=%5B%5B%5D%5D&sf=all&aqe=%5B%5D&sortOrder=author_sort_asc&onlyFullText=false&noOfRows=50&dswid=3619)]

